name: Deploy NH Functions on linux environment

on:
  push:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - "docs/**"

env:
  AZURE_FUNCTIONAPP_NAME: 'az-comm-services-functions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/apps/AzureCommunicationServices/Functions'
  DOTNET_VERSION: '6.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v2

      - name: Configure DotNet Env - ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'dotnet build, restore, release'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Push function app"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
